### PR TITLE
init algorithms

### PR DESCRIPTION
**Pull request by gggin**

### CODE REVIEW

**Comment by gggin** [comment]
impl sha1 with some botan codes, but padding things is done by myself. I have already tested by myself. Maybe use `Catch` test framework to test crypto methods .

**Comment by hanfei1991** [comment]
Compiled error in Linux
```
/home/hanfei/encyption/sha1.cc: In function ‘void load_be(T*, const uint8_t*, size_t)’:
/home/hanfei/encyption/sha1.cc:138:10: error: ‘memcpy’ is not a member of ‘std’
     std::memcpy(out, in, sizeof(T) * count);
          ^~~~~~
/home/hanfei/encyption/sha1.cc:138:10: note: suggested alternative: ‘empty’
     std::memcpy(out, in, sizeof(T) * count);
          ^~~~~~
          empty
/home/hanfei/encyption/sha1.cc: In member function ‘void SHA1Cal::Finish(std::vector<char>&, uint64_t)’:
/home/hanfei/encyption/sha1.cc:355:5: error: ‘memcpy’ was not declared in this scope
     memcpy(reinterpret_cast<char*>(&data.back() - 7),
     ^~~~~~
/home/hanfei/encyption/sha1.cc:355:5: note: suggested alternative: ‘wmemcpy’
     memcpy(reinterpret_cast<char*>(&data.back() - 7),
     ^~~~~~
     wmemcpy
/home/hanfei/encyption/sha1.cc: In member function ‘void SHA1Cal::FileStreamTransform(std::ifstream&)’:
/home/hanfei/encyption/sha1.cc:371:5: error: ‘memset’ was not declared in this scope
     memset(buf.data(), 0, sizeof(char) * BLOCK_SIZE);
     ^~~~~~
/home/hanfei/encyption/sha1.cc:371:5: note: suggested alternative: ‘wmemset’
     memset(buf.data(), 0, sizeof(char) * BLOCK_SIZE);
     ^~~~~~
     wmemset
CMakeFiles/sha1.dir/build.make:62: recipe for target 'CMakeFiles/sha1.dir/sha1.cc.o' failed
make[2]: *** [CMakeFiles/sha1.dir/sha1.cc.o] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/sha1.dir/all' failed
make[1]: *** [CMakeFiles/sha1.dir/all] Error 2
Makefile:83: recipe for target 'all' failed

```

I guess you should include stdlib

**Comment by gggin** [comment]
fixed with easy test picture.
default

**Comment by hanfei1991** [comment]
LGTM

**Pull request merged**
